/* config-parser.c generated by valac, the Vala compiler
 * generated from config-parser.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gstdio.h>


#define TYPE_CONFIG_PARSER (config_parser_get_type ())
#define CONFIG_PARSER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CONFIG_PARSER, ConfigParser))
#define CONFIG_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CONFIG_PARSER, ConfigParserClass))
#define IS_CONFIG_PARSER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CONFIG_PARSER))
#define IS_CONFIG_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CONFIG_PARSER))
#define CONFIG_PARSER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CONFIG_PARSER, ConfigParserClass))

typedef struct _ConfigParser ConfigParser;
typedef struct _ConfigParserClass ConfigParserClass;
typedef struct _ConfigParserPrivate ConfigParserPrivate;
#define _g_markup_parse_context_free0(var) ((var == NULL) ? NULL : (var = (g_markup_parse_context_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_hash_table_unref0(var) ((var == NULL) ? NULL : (var = (g_hash_table_unref (var), NULL)))

struct _ConfigParser {
	GObject parent_instance;
	ConfigParserPrivate * priv;
};

struct _ConfigParserClass {
	GObjectClass parent_class;
};

struct _ConfigParserPrivate {
	GMarkupParseContext* _context;
	char* _current_id;
	GHashTable* _ht;
};


static gpointer config_parser_parent_class = NULL;

GType config_parser_get_type (void);
#define CONFIG_PARSER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_CONFIG_PARSER, ConfigParserPrivate))
enum  {
	CONFIG_PARSER_DUMMY_PROPERTY
};
static void config_parser_start (ConfigParser* self, GMarkupParseContext* context, const char* name, char** attr_names, int attr_names_length1, char** attr_values, int attr_values_length1, GError** error);
static void _config_parser_start_gmarkup_parser_start_element_func (GMarkupParseContext* context, const char* element_name, char** attribute_names, char** attribute_values, gpointer self, GError** error);
static void config_parser_end (ConfigParser* self, GMarkupParseContext* context, const char* name, GError** error);
static void _config_parser_end_gmarkup_parser_end_element_func (GMarkupParseContext* context, const char* element_name, gpointer self, GError** error);
static void config_parser_text (ConfigParser* self, GMarkupParseContext* context, const char* text, gsize text_len, GError** error);
static void _config_parser_text_gmarkup_parser_text_func (GMarkupParseContext* context, const char* text, gsize text_len, gpointer self, GError** error);
char* config_parser_get (ConfigParser* self, const char* key);
gboolean config_parser_parse (ConfigParser* self, const char* content, GError** error);
gboolean config_parser_parse_file (ConfigParser* self, const char* filename, GError** error);
ConfigParser* config_parser_new (void);
ConfigParser* config_parser_construct (GType object_type);
static GObject * config_parser_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void config_parser_finalize (GObject* obj);
static gint _vala_array_length (gpointer array);
static int _vala_strcmp0 (const char * str1, const char * str2);

static const GMarkupParser CONFIG_PARSER__parser = {_config_parser_start_gmarkup_parser_start_element_func, _config_parser_end_gmarkup_parser_end_element_func, _config_parser_text_gmarkup_parser_text_func, NULL, NULL};


static void _config_parser_start_gmarkup_parser_start_element_func (GMarkupParseContext* context, const char* element_name, char** attribute_names, char** attribute_values, gpointer self, GError** error) {
	config_parser_start (self, context, element_name, attribute_names, _vala_array_length (attribute_names), attribute_values, _vala_array_length (attribute_values), error);
}


static void _config_parser_end_gmarkup_parser_end_element_func (GMarkupParseContext* context, const char* element_name, gpointer self, GError** error) {
	config_parser_end (self, context, element_name, error);
}


static void _config_parser_text_gmarkup_parser_text_func (GMarkupParseContext* context, const char* text, gsize text_len, gpointer self, GError** error) {
	config_parser_text (self, context, text, text_len, error);
}


char* config_parser_get (ConfigParser* self, const char* key) {
	char* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (key != NULL, NULL);
	result = g_strdup ((const char*) g_hash_table_lookup (self->priv->_ht, key));
	return result;
}


gboolean config_parser_parse (ConfigParser* self, const char* content, GError** error) {
	gboolean result;
	GError * _inner_error_;
	gboolean _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (content != NULL, FALSE);
	_inner_error_ = NULL;
	_tmp0_ = g_markup_parse_context_parse (self->priv->_context, content, (gssize) (-1), &_inner_error_);
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == G_MARKUP_ERROR) {
			g_propagate_error (error, _inner_error_);
			return FALSE;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return FALSE;
		}
	}
	result = _tmp0_;
	return result;
}


gboolean config_parser_parse_file (ConfigParser* self, const char* filename, GError** error) {
	gboolean result;
	GError * _inner_error_;
	char* content;
	char* _tmp2_;
	gboolean _tmp1_;
	char* _tmp0_ = NULL;
	gboolean _tmp3_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (filename != NULL, FALSE);
	_inner_error_ = NULL;
	content = NULL;
	_tmp3_ = (_tmp1_ = g_file_get_contents (filename, &_tmp0_, NULL, &_inner_error_), content = (_tmp2_ = _tmp0_, _g_free0 (content), _tmp2_), _tmp1_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_g_free0 (content);
		return FALSE;
	}
	if (_tmp3_) {
		gboolean _tmp4_;
		_tmp4_ = config_parser_parse (self, content, &_inner_error_);
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			_g_free0 (content);
			return FALSE;
		}
		result = _tmp4_;
		_g_free0 (content);
		return result;
	}
	result = FALSE;
	_g_free0 (content);
	return result;
}


static void config_parser_start (ConfigParser* self, GMarkupParseContext* context, const char* name, char** attr_names, int attr_names_length1, char** attr_values, int attr_values_length1, GError** error) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (context != NULL);
	g_return_if_fail (name != NULL);
	if (_vala_strcmp0 (name, "pipeline") == 0) {
		guint i;
		const char* attr_name;
		i = (guint) 0;
		attr_name = NULL;
		while (TRUE) {
			if (!((attr_name = attr_names[i]) != NULL)) {
				break;
			}
			if (_vala_strcmp0 (attr_name, "id") == 0) {
				const char* id;
				char* _tmp0_;
				id = attr_values[i];
				self->priv->_current_id = (_tmp0_ = g_strdup (id), _g_free0 (self->priv->_current_id), _tmp0_);
			}
			i++;
		}
	}
}


static void config_parser_end (ConfigParser* self, GMarkupParseContext* context, const char* name, GError** error) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (context != NULL);
	g_return_if_fail (name != NULL);
	self->priv->_current_id = (_tmp0_ = NULL, _g_free0 (self->priv->_current_id), _tmp0_);
}


static char* string_strip (const char* self) {
	char* result;
	char* _result_;
	g_return_val_if_fail (self != NULL, NULL);
	_result_ = g_strdup (self);
	g_strstrip (_result_);
	result = _result_;
	return result;
}


static void config_parser_text (ConfigParser* self, GMarkupParseContext* context, const char* text, gsize text_len, GError** error) {
	char* stripped_text;
	g_return_if_fail (self != NULL);
	g_return_if_fail (context != NULL);
	g_return_if_fail (text != NULL);
	stripped_text = string_strip (text);
	if (self->priv->_current_id != NULL) {
		g_hash_table_insert (self->priv->_ht, g_strdup (self->priv->_current_id), g_strdup (stripped_text));
	} else {
		g_warning ("config-parser.vala:66: Got text '%s' but there is no current pipeline\n", stripped_text);
	}
	_g_free0 (stripped_text);
}


ConfigParser* config_parser_construct (GType object_type) {
	ConfigParser * self;
	self = g_object_newv (object_type, 0, NULL);
	return self;
}


ConfigParser* config_parser_new (void) {
	return config_parser_construct (TYPE_CONFIG_PARSER);
}


static GObject * config_parser_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	ConfigParser * self;
	parent_class = G_OBJECT_CLASS (config_parser_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = CONFIG_PARSER (obj);
	{
		GMarkupParseContext* _tmp0_;
		GHashTable* _tmp1_;
		self->priv->_context = (_tmp0_ = g_markup_parse_context_new (&CONFIG_PARSER__parser, 0, self, NULL), _g_markup_parse_context_free0 (self->priv->_context), _tmp0_);
		self->priv->_ht = (_tmp1_ = g_hash_table_new (g_str_hash, g_str_equal), _g_hash_table_unref0 (self->priv->_ht), _tmp1_);
	}
	return obj;
}


static void config_parser_class_init (ConfigParserClass * klass) {
	config_parser_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ConfigParserPrivate));
	G_OBJECT_CLASS (klass)->constructor = config_parser_constructor;
	G_OBJECT_CLASS (klass)->finalize = config_parser_finalize;
}


static void config_parser_instance_init (ConfigParser * self) {
	self->priv = CONFIG_PARSER_GET_PRIVATE (self);
}


static void config_parser_finalize (GObject* obj) {
	ConfigParser * self;
	self = CONFIG_PARSER (obj);
	_g_markup_parse_context_free0 (self->priv->_context);
	_g_free0 (self->priv->_current_id);
	_g_hash_table_unref0 (self->priv->_ht);
	G_OBJECT_CLASS (config_parser_parent_class)->finalize (obj);
}


GType config_parser_get_type (void) {
	static GType config_parser_type_id = 0;
	if (config_parser_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (ConfigParserClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) config_parser_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ConfigParser), 0, (GInstanceInitFunc) config_parser_instance_init, NULL };
		config_parser_type_id = g_type_register_static (G_TYPE_OBJECT, "ConfigParser", &g_define_type_info, 0);
	}
	return config_parser_type_id;
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




