/* object-list.c generated by valac, the Vala compiler
 * generated from object-list.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define TYPE_OBJECT_LIST (object_list_get_type ())
#define OBJECT_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_OBJECT_LIST, ObjectList))
#define OBJECT_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_OBJECT_LIST, ObjectListClass))
#define IS_OBJECT_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_OBJECT_LIST))
#define IS_OBJECT_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_OBJECT_LIST))
#define OBJECT_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_OBJECT_LIST, ObjectListClass))

typedef struct _ObjectList ObjectList;
typedef struct _ObjectListClass ObjectListClass;
typedef struct _ObjectListPrivate ObjectListPrivate;
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define OBJECT_LIST_TYPE_ITERATOR (object_list_iterator_get_type ())
#define OBJECT_LIST_ITERATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OBJECT_LIST_TYPE_ITERATOR, ObjectListIterator))
#define OBJECT_LIST_ITERATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OBJECT_LIST_TYPE_ITERATOR, ObjectListIteratorClass))
#define OBJECT_LIST_IS_ITERATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OBJECT_LIST_TYPE_ITERATOR))
#define OBJECT_LIST_IS_ITERATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OBJECT_LIST_TYPE_ITERATOR))
#define OBJECT_LIST_ITERATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OBJECT_LIST_TYPE_ITERATOR, ObjectListIteratorClass))

typedef struct _ObjectListIterator ObjectListIterator;
typedef struct _ObjectListIteratorClass ObjectListIteratorClass;
typedef struct _ObjectListIteratorPrivate ObjectListIteratorPrivate;
typedef struct _ObjectListParamSpecIterator ObjectListParamSpecIterator;

struct _ObjectList {
	GObject parent_instance;
	ObjectListPrivate * priv;
};

struct _ObjectListClass {
	GObjectClass parent_class;
};

struct _ObjectListPrivate {
	GType t_type;
	GBoxedCopyFunc t_dup_func;
	GDestroyNotify t_destroy_func;
	GList* _list;
	guint _length;
	char* _name;
};

struct _ObjectListIterator {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ObjectListIteratorPrivate * priv;
};

struct _ObjectListIteratorClass {
	GTypeClass parent_class;
	void (*finalize) (ObjectListIterator *self);
};

struct _ObjectListIteratorPrivate {
	GType t_type;
	GBoxedCopyFunc t_dup_func;
	GDestroyNotify t_destroy_func;
	GList* _iter;
};

struct _ObjectListParamSpecIterator {
	GParamSpec parent_instance;
};


static gpointer object_list_iterator_parent_class = NULL;
static gpointer object_list_parent_class = NULL;

GType object_list_get_type (void);
#define OBJECT_LIST_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_OBJECT_LIST, ObjectListPrivate))
enum  {
	OBJECT_LIST_DUMMY_PROPERTY,
	OBJECT_LIST_LENGTH,
	OBJECT_LIST_NAME,
	OBJECT_LIST_T_TYPE,
	OBJECT_LIST_T_DUP_FUNC,
	OBJECT_LIST_T_DESTROY_FUNC
};
void object_list_append (ObjectList* self, gconstpointer s);
gpointer object_list_get (ObjectList* self, guint i);
ObjectListIterator* object_list_iterator_new (GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func, ObjectList* list);
ObjectListIterator* object_list_iterator_construct (GType object_type, GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func, ObjectList* list);
gpointer object_list_iterator_ref (gpointer instance);
void object_list_iterator_unref (gpointer instance);
GParamSpec* object_list_param_spec_iterator (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void object_list_value_set_iterator (GValue* value, gpointer v_object);
gpointer object_list_value_get_iterator (const GValue* value);
GType object_list_iterator_get_type (void);
ObjectListIterator* object_list_iterator (ObjectList* self);
ObjectList* object_list_new (GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func);
ObjectList* object_list_construct (GType object_type, GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func);
guint object_list_get_length (ObjectList* self);
const char* object_list_get_name (ObjectList* self);
void object_list_set_name (ObjectList* self, const char* value);
static GObject * object_list_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
#define OBJECT_LIST_ITERATOR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), OBJECT_LIST_TYPE_ITERATOR, ObjectListIteratorPrivate))
enum  {
	OBJECT_LIST_ITERATOR_DUMMY_PROPERTY
};
gboolean object_list_iterator_next (ObjectListIterator* self);
gconstpointer object_list_iterator_get (ObjectListIterator* self);
static void object_list_iterator_finalize (ObjectListIterator* obj);
static void object_list_finalize (GObject* obj);
static void object_list_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void object_list_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);



void object_list_append (ObjectList* self, gconstpointer s) {
	gconstpointer _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_list = g_list_append (self->priv->_list, (_tmp0_ = s, ((_tmp0_ == NULL) || (self->priv->t_dup_func == NULL)) ? ((gpointer) _tmp0_) : self->priv->t_dup_func ((gpointer) _tmp0_)));
	self->priv->_length++;
}


gpointer object_list_get (ObjectList* self, guint i) {
	gpointer result;
	gconstpointer _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (i < self->priv->_length, NULL);
	result = (_tmp0_ = g_list_nth_data (self->priv->_list, i), ((_tmp0_ == NULL) || (self->priv->t_dup_func == NULL)) ? ((gpointer) _tmp0_) : self->priv->t_dup_func ((gpointer) _tmp0_));
	return result;
}


ObjectListIterator* object_list_iterator (ObjectList* self) {
	ObjectListIterator* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = object_list_iterator_new (self->priv->t_type, (GBoxedCopyFunc) self->priv->t_dup_func, self->priv->t_destroy_func, self);
	return result;
}


ObjectList* object_list_construct (GType object_type, GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func) {
	GParameter * __params;
	GParameter * __params_it;
	ObjectList * self;
	__params = g_new0 (GParameter, 3);
	__params_it = __params;
	__params_it->name = "t-type";
	g_value_init (&__params_it->value, G_TYPE_GTYPE);
	g_value_set_gtype (&__params_it->value, t_type);
	__params_it++;
	__params_it->name = "t-dup-func";
	g_value_init (&__params_it->value, G_TYPE_POINTER);
	g_value_set_pointer (&__params_it->value, t_dup_func);
	__params_it++;
	__params_it->name = "t-destroy-func";
	g_value_init (&__params_it->value, G_TYPE_POINTER);
	g_value_set_pointer (&__params_it->value, t_destroy_func);
	__params_it++;
	self = g_object_newv (object_type, __params_it - __params, __params);
	while (__params_it > __params) {
		--__params_it;
		g_value_unset (&__params_it->value);
	}
	g_free (__params);
	return self;
}


ObjectList* object_list_new (GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func) {
	return object_list_construct (TYPE_OBJECT_LIST, t_type, t_dup_func, t_destroy_func);
}


guint object_list_get_length (ObjectList* self) {
	guint result;
	g_return_val_if_fail (self != NULL, 0U);
	result = self->priv->_length;
	return result;
}


const char* object_list_get_name (ObjectList* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_name;
	return result;
}


void object_list_set_name (ObjectList* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_name = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_name), _tmp0_);
	g_object_notify ((GObject *) self, "name");
}


static GObject * object_list_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	ObjectList * self;
	parent_class = G_OBJECT_CLASS (object_list_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = OBJECT_LIST (obj);
	{
		GList* _tmp0_;
		self->priv->_list = (_tmp0_ = NULL, _g_list_free0 (self->priv->_list), _tmp0_);
	}
	return obj;
}


ObjectListIterator* object_list_iterator_construct (GType object_type, GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func, ObjectList* list) {
	ObjectListIterator* self;
	g_return_val_if_fail (list != NULL, NULL);
	self = (ObjectListIterator*) g_type_create_instance (object_type);
	self->priv->t_type = t_type;
	self->priv->t_dup_func = t_dup_func;
	self->priv->t_destroy_func = t_destroy_func;
	self->priv->_iter = list->priv->_list;
	return self;
}


ObjectListIterator* object_list_iterator_new (GType t_type, GBoxedCopyFunc t_dup_func, GDestroyNotify t_destroy_func, ObjectList* list) {
	return object_list_iterator_construct (OBJECT_LIST_TYPE_ITERATOR, t_type, t_dup_func, t_destroy_func, list);
}


gboolean object_list_iterator_next (ObjectListIterator* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_iter != NULL;
	return result;
}


gconstpointer object_list_iterator_get (ObjectListIterator* self) {
	gconstpointer result;
	gconstpointer data;
	g_return_val_if_fail (self != NULL, NULL);
	data = self->priv->_iter->data;
	self->priv->_iter = self->priv->_iter->next;
	result = data;
	return result;
}


static void object_list_value_iterator_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void object_list_value_iterator_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		object_list_iterator_unref (value->data[0].v_pointer);
	}
}


static void object_list_value_iterator_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = object_list_iterator_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer object_list_value_iterator_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* object_list_value_iterator_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		ObjectListIterator* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = object_list_iterator_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* object_list_value_iterator_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	ObjectListIterator** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags && G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = object_list_iterator_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* object_list_param_spec_iterator (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ObjectListParamSpecIterator* spec;
	g_return_val_if_fail (g_type_is_a (object_type, OBJECT_LIST_TYPE_ITERATOR), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer object_list_value_get_iterator (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, OBJECT_LIST_TYPE_ITERATOR), NULL);
	return value->data[0].v_pointer;
}


void object_list_value_set_iterator (GValue* value, gpointer v_object) {
	ObjectListIterator* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, OBJECT_LIST_TYPE_ITERATOR));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, OBJECT_LIST_TYPE_ITERATOR));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		object_list_iterator_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		object_list_iterator_unref (old);
	}
}


static void object_list_iterator_class_init (ObjectListIteratorClass * klass) {
	object_list_iterator_parent_class = g_type_class_peek_parent (klass);
	OBJECT_LIST_ITERATOR_CLASS (klass)->finalize = object_list_iterator_finalize;
	g_type_class_add_private (klass, sizeof (ObjectListIteratorPrivate));
}


static void object_list_iterator_instance_init (ObjectListIterator * self) {
	self->priv = OBJECT_LIST_ITERATOR_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void object_list_iterator_finalize (ObjectListIterator* obj) {
	ObjectListIterator * self;
	self = OBJECT_LIST_ITERATOR (obj);
}


GType object_list_iterator_get_type (void) {
	static GType object_list_iterator_type_id = 0;
	if (object_list_iterator_type_id == 0) {
		static const GTypeValueTable g_define_type_value_table = { object_list_value_iterator_init, object_list_value_iterator_free_value, object_list_value_iterator_copy_value, object_list_value_iterator_peek_pointer, "p", object_list_value_iterator_collect_value, "p", object_list_value_iterator_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (ObjectListIteratorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) object_list_iterator_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ObjectListIterator), 0, (GInstanceInitFunc) object_list_iterator_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		object_list_iterator_type_id = g_type_register_fundamental (g_type_fundamental_next (), "ObjectListIterator", &g_define_type_info, &g_define_type_fundamental_info, 0);
	}
	return object_list_iterator_type_id;
}


gpointer object_list_iterator_ref (gpointer instance) {
	ObjectListIterator* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void object_list_iterator_unref (gpointer instance) {
	ObjectListIterator* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		OBJECT_LIST_ITERATOR_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void object_list_class_init (ObjectListClass * klass) {
	object_list_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ObjectListPrivate));
	G_OBJECT_CLASS (klass)->get_property = object_list_get_property;
	G_OBJECT_CLASS (klass)->set_property = object_list_set_property;
	G_OBJECT_CLASS (klass)->constructor = object_list_constructor;
	G_OBJECT_CLASS (klass)->finalize = object_list_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), OBJECT_LIST_T_TYPE, g_param_spec_gtype ("t-type", "type", "type", G_TYPE_NONE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OBJECT_LIST_T_DUP_FUNC, g_param_spec_pointer ("t-dup-func", "dup func", "dup func", G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OBJECT_LIST_T_DESTROY_FUNC, g_param_spec_pointer ("t-destroy-func", "destroy func", "destroy func", G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OBJECT_LIST_LENGTH, g_param_spec_uint ("length", "length", "length", 0, G_MAXUINT, 0U, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), OBJECT_LIST_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void object_list_instance_init (ObjectList * self) {
	self->priv = OBJECT_LIST_GET_PRIVATE (self);
}


static void object_list_finalize (GObject* obj) {
	ObjectList * self;
	self = OBJECT_LIST (obj);
	_g_list_free0 (self->priv->_list);
	_g_free0 (self->priv->_name);
	G_OBJECT_CLASS (object_list_parent_class)->finalize (obj);
}


GType object_list_get_type (void) {
	static GType object_list_type_id = 0;
	if (object_list_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (ObjectListClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) object_list_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ObjectList), 0, (GInstanceInitFunc) object_list_instance_init, NULL };
		object_list_type_id = g_type_register_static (G_TYPE_OBJECT, "ObjectList", &g_define_type_info, 0);
	}
	return object_list_type_id;
}


static void object_list_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	ObjectList * self;
	self = OBJECT_LIST (object);
	switch (property_id) {
		case OBJECT_LIST_LENGTH:
		g_value_set_uint (value, object_list_get_length (self));
		break;
		case OBJECT_LIST_NAME:
		g_value_set_string (value, object_list_get_name (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void object_list_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	ObjectList * self;
	self = OBJECT_LIST (object);
	switch (property_id) {
		case OBJECT_LIST_NAME:
		object_list_set_name (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
		case OBJECT_LIST_T_TYPE:
		self->priv->t_type = g_value_get_gtype (value);
		break;
		case OBJECT_LIST_T_DUP_FUNC:
		self->priv->t_dup_func = g_value_get_pointer (value);
		break;
		case OBJECT_LIST_T_DESTROY_FUNC:
		self->priv->t_destroy_func = g_value_get_pointer (value);
		break;
	}
}




