/* task.c generated by valac, the Vala compiler
 * generated from task.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_TASK (task_get_type ())
#define TASK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TASK, Task))
#define TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TASK, TaskClass))
#define IS_TASK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TASK))
#define IS_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TASK))
#define TASK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TASK, TaskClass))

typedef struct _Task Task;
typedef struct _TaskClass TaskClass;
typedef struct _TaskPrivate TaskPrivate;

#define TYPE_COMMAND (command_get_type ())

#define TYPE_AUTO_PIPELINE (auto_pipeline_get_type ())
#define AUTO_PIPELINE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_AUTO_PIPELINE, AutoPipeline))
#define AUTO_PIPELINE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_AUTO_PIPELINE, AutoPipelineClass))
#define IS_AUTO_PIPELINE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_AUTO_PIPELINE))
#define IS_AUTO_PIPELINE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_AUTO_PIPELINE))
#define AUTO_PIPELINE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_AUTO_PIPELINE, AutoPipelineClass))

typedef struct _AutoPipeline AutoPipeline;
typedef struct _AutoPipelineClass AutoPipelineClass;
typedef struct _Command Command;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block1Data Block1Data;

struct _Task {
	GObject parent_instance;
	TaskPrivate * priv;
};

struct _TaskClass {
	GObjectClass parent_class;
};

typedef void (*CommandFunc) (AutoPipeline* ctx, void* user_data);
struct _Command {
	char* name;
	char* description;
	CommandFunc function;
	gpointer function_target;
	GDestroyNotify function_target_destroy_notify;
};

struct _TaskPrivate {
	double _seconds;
	Command* _command;
};

struct _Block1Data {
	int _ref_count_;
	Task * self;
	AutoPipeline* ctx;
};


static gpointer task_parent_class = NULL;

GType task_get_type (void);
GType command_get_type (void);
GType auto_pipeline_get_type (void);
Command* command_dup (const Command* self);
void command_free (Command* self);
void command_copy (const Command* self, Command* dest);
void command_destroy (Command* self);
#define TASK_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_TASK, TaskPrivate))
enum  {
	TASK_DUMMY_PROPERTY,
	TASK_SECONDS
};
Task* task_new (double seconds, Command* command);
Task* task_construct (GType object_type, double seconds, Command* command);
double task_get_seconds (Task* self);
GTimer* auto_pipeline_get_timer (AutoPipeline* self);
static gboolean _lambda0_ (Block1Data* _data1_);
static gboolean __lambda0__gsource_func (gpointer self);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (Block1Data* _data1_);
guint task_exec (Task* self, AutoPipeline* ctx);
static void task_finalize (GObject* obj);
static void task_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);



Task* task_construct (GType object_type, double seconds, Command* command) {
	Task * self;
	self = (Task*) g_object_new (object_type, NULL);
	self->priv->_seconds = seconds;
	self->priv->_command = command;
	return self;
}


Task* task_new (double seconds, Command* command) {
	return task_construct (TYPE_TASK, seconds, command);
}


static gboolean _lambda0_ (Block1Data* _data1_) {
	Task * self;
	gboolean result;
	self = _data1_->self;
	g_print ("Time = %lf\n", g_timer_elapsed (auto_pipeline_get_timer (_data1_->ctx), NULL));
	(*self->priv->_command).function (_data1_->ctx, (*self->priv->_command).function_target);
	result = FALSE;
	return result;
}


static gboolean __lambda0__gsource_func (gpointer self) {
	return _lambda0_ (self);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
	++_data1_->_ref_count_;
	return _data1_;
}


static void block1_data_unref (Block1Data* _data1_) {
	if ((--_data1_->_ref_count_) == 0) {
		_g_object_unref0 (_data1_->self);
		_g_object_unref0 (_data1_->ctx);
		g_slice_free (Block1Data, _data1_);
	}
}


guint task_exec (Task* self, AutoPipeline* ctx) {
	guint result;
	Block1Data* _data1_;
	g_return_val_if_fail (self != NULL, 0U);
	g_return_val_if_fail (ctx != NULL, 0U);
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	_data1_->self = g_object_ref (self);
	_data1_->ctx = _g_object_ref0 (ctx);
	result = g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) (task_get_seconds (self) * 1000), __lambda0__gsource_func, block1_data_ref (_data1_), block1_data_unref);
	block1_data_unref (_data1_);
	return result;
}


double task_get_seconds (Task* self) {
	double result;
	g_return_val_if_fail (self != NULL, 0.0);
	result = self->priv->_seconds;
	return result;
}


static void task_class_init (TaskClass * klass) {
	task_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (TaskPrivate));
	G_OBJECT_CLASS (klass)->get_property = task_get_property;
	G_OBJECT_CLASS (klass)->finalize = task_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), TASK_SECONDS, g_param_spec_double ("seconds", "seconds", "seconds", -G_MAXDOUBLE, G_MAXDOUBLE, 0.0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void task_instance_init (Task * self) {
	self->priv = TASK_GET_PRIVATE (self);
}


static void task_finalize (GObject* obj) {
	Task * self;
	self = TASK (obj);
	G_OBJECT_CLASS (task_parent_class)->finalize (obj);
}


GType task_get_type (void) {
	static GType task_type_id = 0;
	if (task_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (TaskClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) task_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Task), 0, (GInstanceInitFunc) task_instance_init, NULL };
		task_type_id = g_type_register_static (G_TYPE_OBJECT, "Task", &g_define_type_info, 0);
	}
	return task_type_id;
}


static void task_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	Task * self;
	self = TASK (object);
	switch (property_id) {
		case TASK_SECONDS:
		g_value_set_double (value, task_get_seconds (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}




