/* xml-parser.c generated by valac, the Vala compiler
 * generated from xml-parser.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gstdio.h>


#define TYPE_XML_PARSER (xml_parser_get_type ())
#define XML_PARSER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_XML_PARSER, XmlParser))
#define XML_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_XML_PARSER, XmlParserClass))
#define IS_XML_PARSER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_XML_PARSER))
#define IS_XML_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_XML_PARSER))
#define XML_PARSER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_XML_PARSER, XmlParserClass))

typedef struct _XmlParser XmlParser;
typedef struct _XmlParserClass XmlParserClass;
typedef struct _XmlParserPrivate XmlParserPrivate;
#define _g_markup_parse_context_free0(var) ((var == NULL) ? NULL : (var = (g_markup_parse_context_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_hash_table_unref0(var) ((var == NULL) ? NULL : (var = (g_hash_table_unref (var), NULL)))

struct _XmlParser {
	GObject parent_instance;
	XmlParserPrivate * priv;
};

struct _XmlParserClass {
	GObjectClass parent_class;
};

struct _XmlParserPrivate {
	GMarkupParseContext* _context;
	char* _current_id;
	GHashTable* _ht;
};


static gpointer xml_parser_parent_class = NULL;

GType xml_parser_get_type (void);
#define XML_PARSER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_XML_PARSER, XmlParserPrivate))
enum  {
	XML_PARSER_DUMMY_PROPERTY
};
static void xml_parser_start (XmlParser* self, GMarkupParseContext* context, const char* name, char** attr_names, int attr_names_length1, char** attr_values, int attr_values_length1, GError** error);
static void _xml_parser_start_gmarkup_parser_start_element_func (GMarkupParseContext* context, const char* element_name, char** attribute_names, char** attribute_values, gpointer self, GError** error);
static void xml_parser_end (XmlParser* self, GMarkupParseContext* context, const char* name, GError** error);
static void _xml_parser_end_gmarkup_parser_end_element_func (GMarkupParseContext* context, const char* element_name, gpointer self, GError** error);
static void xml_parser_text (XmlParser* self, GMarkupParseContext* context, const char* text, gsize text_len, GError** error);
static void _xml_parser_text_gmarkup_parser_text_func (GMarkupParseContext* context, const char* text, gsize text_len, gpointer self, GError** error);
char* xml_parser_get (XmlParser* self, const char* key);
gboolean xml_parser_parse (XmlParser* self, const char* content, GError** error);
gboolean xml_parser_parse_file (XmlParser* self, const char* filename, GError** error);
XmlParser* xml_parser_new (void);
XmlParser* xml_parser_construct (GType object_type);
static GObject * xml_parser_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void xml_parser_finalize (GObject* obj);
static gint _vala_array_length (gpointer array);
static int _vala_strcmp0 (const char * str1, const char * str2);

static const GMarkupParser XML_PARSER__parser = {_xml_parser_start_gmarkup_parser_start_element_func, _xml_parser_end_gmarkup_parser_end_element_func, _xml_parser_text_gmarkup_parser_text_func, NULL, NULL};


static void _xml_parser_start_gmarkup_parser_start_element_func (GMarkupParseContext* context, const char* element_name, char** attribute_names, char** attribute_values, gpointer self, GError** error) {
	xml_parser_start (self, context, element_name, attribute_names, _vala_array_length (attribute_names), attribute_values, _vala_array_length (attribute_values), error);
}


static void _xml_parser_end_gmarkup_parser_end_element_func (GMarkupParseContext* context, const char* element_name, gpointer self, GError** error) {
	xml_parser_end (self, context, element_name, error);
}


static void _xml_parser_text_gmarkup_parser_text_func (GMarkupParseContext* context, const char* text, gsize text_len, gpointer self, GError** error) {
	xml_parser_text (self, context, text, text_len, error);
}


char* xml_parser_get (XmlParser* self, const char* key) {
	char* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (key != NULL, NULL);
	result = g_strdup ((const char*) g_hash_table_lookup (self->priv->_ht, key));
	return result;
}


gboolean xml_parser_parse (XmlParser* self, const char* content, GError** error) {
	gboolean result;
	GError * _inner_error_;
	gboolean _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (content != NULL, FALSE);
	_inner_error_ = NULL;
	_tmp0_ = g_markup_parse_context_parse (self->priv->_context, content, (gssize) (-1), &_inner_error_);
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == G_MARKUP_ERROR) {
			g_propagate_error (error, _inner_error_);
			return FALSE;
		} else {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return FALSE;
		}
	}
	result = _tmp0_;
	return result;
}


gboolean xml_parser_parse_file (XmlParser* self, const char* filename, GError** error) {
	gboolean result;
	GError * _inner_error_;
	char* content;
	char* _tmp2_;
	gboolean _tmp1_;
	char* _tmp0_ = NULL;
	gboolean _tmp3_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (filename != NULL, FALSE);
	_inner_error_ = NULL;
	content = NULL;
	_tmp3_ = (_tmp1_ = g_file_get_contents (filename, &_tmp0_, NULL, &_inner_error_), content = (_tmp2_ = _tmp0_, _g_free0 (content), _tmp2_), _tmp1_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_g_free0 (content);
		return FALSE;
	}
	if (_tmp3_) {
		gboolean _tmp4_;
		_tmp4_ = xml_parser_parse (self, content, &_inner_error_);
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			_g_free0 (content);
			return FALSE;
		}
		result = _tmp4_;
		_g_free0 (content);
		return result;
	}
	result = FALSE;
	_g_free0 (content);
	return result;
}


static void xml_parser_start (XmlParser* self, GMarkupParseContext* context, const char* name, char** attr_names, int attr_names_length1, char** attr_values, int attr_values_length1, GError** error) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (context != NULL);
	g_return_if_fail (name != NULL);
	if (_vala_strcmp0 (name, "pipeline") == 0) {
		guint i;
		const char* attr_name;
		i = (guint) 0;
		attr_name = NULL;
		while (TRUE) {
			if (!((attr_name = attr_names[i]) != NULL)) {
				break;
			}
			if (_vala_strcmp0 (attr_name, "id") == 0) {
				const char* id;
				char* _tmp0_;
				id = attr_values[i];
				self->priv->_current_id = (_tmp0_ = g_strdup (id), _g_free0 (self->priv->_current_id), _tmp0_);
			}
			i++;
		}
	}
}


static void xml_parser_end (XmlParser* self, GMarkupParseContext* context, const char* name, GError** error) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (context != NULL);
	g_return_if_fail (name != NULL);
	self->priv->_current_id = (_tmp0_ = NULL, _g_free0 (self->priv->_current_id), _tmp0_);
}


static char* string_strip (const char* self) {
	char* result;
	char* _result_;
	g_return_val_if_fail (self != NULL, NULL);
	_result_ = g_strdup (self);
	g_strstrip (_result_);
	result = _result_;
	return result;
}


static void xml_parser_text (XmlParser* self, GMarkupParseContext* context, const char* text, gsize text_len, GError** error) {
	char* stripped_text;
	g_return_if_fail (self != NULL);
	g_return_if_fail (context != NULL);
	g_return_if_fail (text != NULL);
	stripped_text = string_strip (text);
	if (self->priv->_current_id != NULL) {
		g_hash_table_insert (self->priv->_ht, g_strdup (self->priv->_current_id), g_strdup (stripped_text));
	} else {
		g_warning ("xml-parser.vala:66: Got text '%s' but there is no current pipeline\n", stripped_text);
	}
	_g_free0 (stripped_text);
}


XmlParser* xml_parser_construct (GType object_type) {
	XmlParser * self;
	self = g_object_newv (object_type, 0, NULL);
	return self;
}


XmlParser* xml_parser_new (void) {
	return xml_parser_construct (TYPE_XML_PARSER);
}


static GObject * xml_parser_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	XmlParser * self;
	parent_class = G_OBJECT_CLASS (xml_parser_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = XML_PARSER (obj);
	{
		GMarkupParseContext* _tmp0_;
		GHashTable* _tmp1_;
		self->priv->_context = (_tmp0_ = g_markup_parse_context_new (&XML_PARSER__parser, 0, self, NULL), _g_markup_parse_context_free0 (self->priv->_context), _tmp0_);
		self->priv->_ht = (_tmp1_ = g_hash_table_new (g_str_hash, g_str_equal), _g_hash_table_unref0 (self->priv->_ht), _tmp1_);
	}
	return obj;
}


static void xml_parser_class_init (XmlParserClass * klass) {
	xml_parser_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (XmlParserPrivate));
	G_OBJECT_CLASS (klass)->constructor = xml_parser_constructor;
	G_OBJECT_CLASS (klass)->finalize = xml_parser_finalize;
}


static void xml_parser_instance_init (XmlParser * self) {
	self->priv = XML_PARSER_GET_PRIVATE (self);
}


static void xml_parser_finalize (GObject* obj) {
	XmlParser * self;
	self = XML_PARSER (obj);
	_g_markup_parse_context_free0 (self->priv->_context);
	_g_free0 (self->priv->_current_id);
	_g_hash_table_unref0 (self->priv->_ht);
	G_OBJECT_CLASS (xml_parser_parent_class)->finalize (obj);
}


GType xml_parser_get_type (void) {
	static GType xml_parser_type_id = 0;
	if (xml_parser_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (XmlParserClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xml_parser_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (XmlParser), 0, (GInstanceInitFunc) xml_parser_instance_init, NULL };
		xml_parser_type_id = g_type_register_static (G_TYPE_OBJECT, "XmlParser", &g_define_type_info, 0);
	}
	return xml_parser_type_id;
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




